DROP TABLE ATTACHMENTS;
CREATE TABLE ATTACHMENTS (id int NOT NULL AUTO_INCREMENT, post_id int NOT NULL, type varchar(100) NOT NULL, url text NOT NULL, is_local tinyint(1) DEFAULT 1 NOT NULL, PRIMARY KEY (id), INDEX post_id (post_id)) ENGINE=InnoDB DEFAULT CHARSET=latin1 DEFAULT COLLATE=latin1_swedish_ci;
DROP TABLE CATEGORIES;
CREATE TABLE CATEGORIES (id int NOT NULL AUTO_INCREMENT, name varchar(255), PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=latin1 DEFAULT COLLATE=latin1_swedish_ci;
DROP TABLE COMMENTS;
CREATE TABLE COMMENTS (id int NOT NULL AUTO_INCREMENT, post_id int NOT NULL, reply_id int, content text NOT NULL, PRIMARY KEY (id), INDEX post_id (post_id), INDEX reply_id (reply_id)) ENGINE=InnoDB DEFAULT CHARSET=latin1 DEFAULT COLLATE=latin1_swedish_ci;
DROP TABLE POSTS;
CREATE TABLE POSTS (id int NOT NULL AUTO_INCREMENT, user_id varchar(200) NOT NULL, category_id int NOT NULL, title text, description text, tags text, image_url text, created_at datetime, updated_at datetime, deleted tinyint(1) DEFAULT 0 NOT NULL, is_blog tinyint(1) DEFAULT 0 NOT NULL, PRIMARY KEY (id), INDEX user_id (user_id), INDEX category_id (category_id)) ENGINE=InnoDB DEFAULT CHARSET=latin1 DEFAULT COLLATE=latin1_swedish_ci;
DROP TABLE RATING;
CREATE TABLE RATING (user_id varchar(200) NOT NULL, post_id int NOT NULL, rating tinyint NOT NULL, PRIMARY KEY (post_id, user_id), INDEX user_id (user_id)) ENGINE=InnoDB DEFAULT CHARSET=latin1 DEFAULT COLLATE=latin1_swedish_ci;
DROP TABLE TAGS;
CREATE TABLE TAGS (name varchar(255) NOT NULL, PRIMARY KEY (name)) ENGINE=InnoDB DEFAULT CHARSET=latin1 DEFAULT COLLATE=latin1_swedish_ci;
DROP TABLE USERS;
CREATE TABLE USERS (id varchar(200) NOT NULL, username varchar(50), full_name text, is_active tinyint(1) DEFAULT 1 NOT NULL, PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=latin1 DEFAULT COLLATE=latin1_swedish_ci;
ALTER TABLE `ATTACHMENTS` ADD FOREIGN KEY (`post_id`) REFERENCES `POSTS` (`id`);
ALTER TABLE `COMMENTS` ADD FOREIGN KEY (`post_id`) REFERENCES `POSTS` (`id`) ;
ALTER TABLE `COMMENTS` ADD FOREIGN KEY (`reply_id`) REFERENCES `COMMENTS` (`id`);
ALTER TABLE `POSTS` ADD FOREIGN KEY (`user_id`) REFERENCES `USERS` (`id`) ;
ALTER TABLE `POSTS` ADD FOREIGN KEY (`category_id`) REFERENCES `CATEGORIES` (`id`);
ALTER TABLE `RATING` ADD FOREIGN KEY (`post_id`) REFERENCES `POSTS` (`id`) ;
ALTER TABLE `RATING` ADD FOREIGN KEY (`user_id`) REFERENCES `USERS` (`id`);
