DROP TABLE ATTACHMENTS;
CREATE TABLE ATTACHMENTS (id int NOT NULL AUTO_INCREMENT, post_id int NOT NULL, type varchar(100) NOT NULL, url text NOT NULL, is_local tinyint(1) DEFAULT 1 NOT NULL, PRIMARY KEY (id), INDEX post_id (post_id)) ENGINE=InnoDB DEFAULT CHARSET=latin1 DEFAULT COLLATE=latin1_swedish_ci;
DROP TABLE CATEGORIES;
CREATE TABLE CATEGORIES (id int NOT NULL AUTO_INCREMENT, name varchar(255), PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=latin1 DEFAULT COLLATE=latin1_swedish_ci;
INSERT INTO CATEGORIES (id, name) VALUES (1, 'Computer Science');
INSERT INTO CATEGORIES (id, name) VALUES (2, 'Information System');
INSERT INTO CATEGORIES (id, name) VALUES (3, 'Accounting');
INSERT INTO CATEGORIES (id, name) VALUES (4, 'Finance');
INSERT INTO CATEGORIES (id, name) VALUES (5, 'Business');
DROP TABLE COMMENTS;
CREATE TABLE COMMENTS (id int NOT NULL AUTO_INCREMENT, post_id int NOT NULL, reply_id int, content text NOT NULL, PRIMARY KEY (id), INDEX post_id (post_id), INDEX reply_id (reply_id)) ENGINE=InnoDB DEFAULT CHARSET=latin1 DEFAULT COLLATE=latin1_swedish_ci;
DROP TABLE POSTS;
CREATE TABLE POSTS (id int NOT NULL AUTO_INCREMENT, user_id varchar(200) NOT NULL, category_id int NOT NULL, title text, description text, tags text, image_url text, created_at datetime, updated_at datetime, deleted tinyint(1) DEFAULT 0 NOT NULL, is_blog tinyint(1) DEFAULT 0 NOT NULL, PRIMARY KEY (id), INDEX user_id (user_id), INDEX category_id (category_id)) ENGINE=InnoDB DEFAULT CHARSET=latin1 DEFAULT COLLATE=latin1_swedish_ci;
INSERT INTO POSTS (id, user_id, category_id, title, description, tags, image_url, created_at, updated_at, deleted, is_blog) VALUES (1, 'cZLhIvl5csbqk0P8SLhjBE18may1', 1, 'This is a first post', '### This is a first blog

![](https://www.cbronline.com/wp-content/uploads/2016/07/HTTP-770x513.jpg)

Do you like this picture', '#computer #nicepicture', 'images/2019-11-11T23-09-28.051Z-bg-1.jpg', '2019-11-11 23:09:28', '2019-11-11 23:09:28', false, true);
INSERT INTO POSTS (id, user_id, category_id, title, description, tags, image_url, created_at, updated_at, deleted, is_blog) VALUES (2, 'cZLhIvl5csbqk0P8SLhjBE18may1', 3, 'How to calculate BC Tax', '### This is a second post

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique. Diam quis enim lobortis scelerisque fermentum dui. Morbi tristique senectus et netus et malesuada fames. Pretium lectus quam id leo in vitae turpis massa. Suspendisse in est ante in nibh mauris. Id cursus metus aliquam eleifend mi in. Lectus proin nibh nisl condimentum id venenatis a condimentum. Turpis egestas pretium aenean pharetra magna ac placerat. Mauris vitae ultricies leo integer malesuada nunc vel risus commodo. Netus et malesuada fames ac turpis egestas integer eget.

Facilisi nullam vehicula ipsum a arcu cursus. Dolor purus non enim praesent elementum facilisis leo vel. Elementum sagittis vitae et leo. Porttitor eget dolor morbi non arcu risus quis varius quam. Arcu ac tortor dignissim convallis aenean et tortor. Et magnis dis parturient montes nascetur. Varius morbi enim nunc faucibus. Sem nulla pharetra diam sit amet nisl suscipit adipiscing bibendum. Tempor commodo ullamcorper a lacus vestibulum sed arcu non. Consectetur adipiscing elit ut aliquam purus sit amet luctus venenatis.

Proin libero nunc consequat interdum varius sit amet mattis. Platea dictumst quisque sagittis purus sit amet volutpat consequat. Adipiscing commodo elit at imperdiet dui accumsan. Eget aliquet nibh praesent tristique magna. Quis vel eros donec ac. Consequat ac felis donec et odio pellentesque diam volutpat commodo. Blandit libero volutpat sed cras ornare arcu dui. Vulputate mi sit amet mauris commodo quis. Nunc scelerisque viverra mauris in aliquam sem. Erat nam at lectus urna duis convallis. Habitasse platea dictumst vestibulum rhoncus est.

Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Diam maecenas ultricies mi eget mauris pharetra. Elit at imperdiet dui accumsan. Sodales neque sodales ut etiam sit amet nisl. Suspendisse in est ante in nibh mauris cursus mattis molestie. Tortor at auctor urna nunc id cursus metus aliquam. Risus at ultrices mi tempus imperdiet nulla malesuada pellentesque elit. At erat pellentesque adipiscing commodo elit at. Aliquam id diam maecenas ultricies mi eget mauris pharetra et. Scelerisque viverra mauris in aliquam sem fringilla. Rhoncus urna neque viverra justo. A diam maecenas sed enim ut sem viverra aliquet eget. Fusce ut placerat orci nulla pellentesque. Etiam dignissim diam quis enim lobortis scelerisque fermentum dui. Eu consequat ac felis donec et. Nisl nisi scelerisque eu ultrices vitae auctor eu augue ut. Cras pulvinar mattis nunc sed. Nunc sed velit dignissim sodales ut eu sem. Rutrum tellus pellentesque eu tincidunt tortor aliquam. Nec nam aliquam sem et.

Dolor sed viverra ipsum nunc aliquet bibendum enim facilisis gravida. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus in. Et ligula ullamcorper malesuada proin libero nunc consequat interdum varius. Magna etiam tempor orci eu lobortis elementum nibh tellus molestie. Purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Semper eget duis at tellus at urna condimentum mattis pellentesque. Diam sit amet nisl suscipit adipiscing bibendum est ultricies integer. Sed ullamcorper morbi tincidunt ornare massa. Tellus orci ac auctor augue mauris augue neque gravida in. Ipsum consequat nisl vel pretium lectus quam. Penatibus et magnis dis parturient montes. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. A pellentesque sit amet porttitor eget. Aliquet risus feugiat in ante. Est ultricies integer quis auctor elit sed vulputate. Turpis egestas maecenas pharetra convallis posuere morbi leo. Ut morbi tincidunt augue interdum velit euismod in pellentesque. Semper eget duis at tellus at urna. A diam maecenas sed enim ut sem viverra aliquet. Nunc scelerisque viverra mauris in aliquam sem fringilla ut morbi.', '#bctax #', 'images/2019-11-11T23-53-30.897Z-bg-2.jpg', '2019-11-11 23:53:30', '2019-11-11 23:53:30', false, true);
INSERT INTO POSTS (id, user_id, category_id, title, description, tags, image_url, created_at, updated_at, deleted, is_blog) VALUES (3, 'cZLhIvl5csbqk0P8SLhjBE18may1', 2, 'How to set up LAMP on Linux', '### This is a third post 



Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique. Diam quis enim lobortis scelerisque fermentum dui. Morbi tristique senectus et netus et malesuada fames. Pretium lectus quam id leo in vitae turpis massa. Suspendisse in est ante in nibh mauris. Id cursus metus aliquam eleifend mi in. Lectus proin nibh nisl condimentum id venenatis a condimentum. Turpis egestas pretium aenean pharetra magna ac placerat. Mauris vitae ultricies leo integer malesuada nunc vel risus commodo. Netus et malesuada fames ac turpis egestas integer eget.

Facilisi nullam vehicula ipsum a arcu cursus. Dolor purus non enim praesent elementum facilisis leo vel. Elementum sagittis vitae et leo. Porttitor eget dolor morbi non arcu risus quis varius quam. Arcu ac tortor dignissim convallis aenean et tortor. Et magnis dis parturient montes nascetur. Varius morbi enim nunc faucibus. Sem nulla pharetra diam sit amet nisl suscipit adipiscing bibendum. Tempor commodo ullamcorper a lacus vestibulum sed arcu non. Consectetur adipiscing elit ut aliquam purus sit amet luctus venenatis.

Proin libero nunc consequat interdum varius sit amet mattis. Platea dictumst quisque sagittis purus sit amet volutpat consequat. Adipiscing commodo elit at imperdiet dui accumsan. Eget aliquet nibh praesent tristique magna. Quis vel eros donec ac. Consequat ac felis donec et odio pellentesque diam volutpat commodo. Blandit libero volutpat sed cras ornare arcu dui. Vulputate mi sit amet mauris commodo quis. Nunc scelerisque viverra mauris in aliquam sem. Erat nam at lectus urna duis convallis. Habitasse platea dictumst vestibulum rhoncus est.

Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Diam maecenas ultricies mi eget mauris pharetra. Elit at imperdiet dui accumsan. Sodales neque sodales ut etiam sit amet nisl. Suspendisse in est ante in nibh mauris cursus mattis molestie. Tortor at auctor urna nunc id cursus metus aliquam. Risus at ultrices mi tempus imperdiet nulla malesuada pellentesque elit. At erat pellentesque adipiscing commodo elit at. Aliquam id diam maecenas ultricies mi eget mauris pharetra et. Scelerisque viverra mauris in aliquam sem fringilla. Rhoncus urna neque viverra justo. A diam maecenas sed enim ut sem viverra aliquet eget. Fusce ut placerat orci nulla pellentesque. Etiam dignissim diam quis enim lobortis scelerisque fermentum dui. Eu consequat ac felis donec et. Nisl nisi scelerisque eu ultrices vitae auctor eu augue ut. Cras pulvinar mattis nunc sed. Nunc sed velit dignissim sodales ut eu sem. Rutrum tellus pellentesque eu tincidunt tortor aliquam. Nec nam aliquam sem et.

Dolor sed viverra ipsum nunc aliquet bibendum enim facilisis gravida. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus in. Et ligula ullamcorper malesuada proin libero nunc consequat interdum varius. Magna etiam tempor orci eu lobortis elementum nibh tellus molestie. Purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Semper eget duis at tellus at urna condimentum mattis pellentesque. Diam sit amet nisl suscipit adipiscing bibendum est ultricies integer. Sed ullamcorper morbi tincidunt ornare massa. Tellus orci ac auctor augue mauris augue neque gravida in. Ipsum consequat nisl vel pretium lectus quam. Penatibus et magnis dis parturient montes. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. A pellentesque sit amet porttitor eget. Aliquet risus feugiat in ante. Est ultricies integer quis auctor elit sed vulputate. Turpis egestas maecenas pharetra convallis posuere morbi leo. Ut morbi tincidunt augue interdum velit euismod in pellentesque. Semper eget duis at tellus at urna. A diam maecenas sed enim ut sem viverra aliquet. Nunc scelerisque viverra mauris in aliquam sem fringilla ut morbi.', '#computer #lamp #unix', 'images/2019-11-12T00-00-02.385Z-bg-12.jpg', '2019-11-12 00:00:02', '2019-11-12 00:00:02', false, true);
INSERT INTO POSTS (id, user_id, category_id, title, description, tags, image_url, created_at, updated_at, deleted, is_blog) VALUES (4, 'cZLhIvl5csbqk0P8SLhjBE18may1', 2, 'Docker Swarm vs Kubernetes', '### This is a 4th post

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique. Diam quis enim lobortis scelerisque fermentum dui. Morbi tristique senectus et netus et malesuada fames. Pretium lectus quam id leo in vitae turpis massa. Suspendisse in est ante in nibh mauris. Id cursus metus aliquam eleifend mi in. Lectus proin nibh nisl condimentum id venenatis a condimentum. Turpis egestas pretium aenean pharetra magna ac placerat. Mauris vitae ultricies leo integer malesuada nunc vel risus commodo. Netus et malesuada fames ac turpis egestas integer eget.

Facilisi nullam vehicula ipsum a arcu cursus. Dolor purus non enim praesent elementum facilisis leo vel. Elementum sagittis vitae et leo. Porttitor eget dolor morbi non arcu risus quis varius quam. Arcu ac tortor dignissim convallis aenean et tortor. Et magnis dis parturient montes nascetur. Varius morbi enim nunc faucibus. Sem nulla pharetra diam sit amet nisl suscipit adipiscing bibendum. Tempor commodo ullamcorper a lacus vestibulum sed arcu non. Consectetur adipiscing elit ut aliquam purus sit amet luctus venenatis.

Proin libero nunc consequat interdum varius sit amet mattis. Platea dictumst quisque sagittis purus sit amet volutpat consequat. Adipiscing commodo elit at imperdiet dui accumsan. Eget aliquet nibh praesent tristique magna. Quis vel eros donec ac. Consequat ac felis donec et odio pellentesque diam volutpat commodo. Blandit libero volutpat sed cras ornare arcu dui. Vulputate mi sit amet mauris commodo quis. Nunc scelerisque viverra mauris in aliquam sem. Erat nam at lectus urna duis convallis. Habitasse platea dictumst vestibulum rhoncus est.

Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Diam maecenas ultricies mi eget mauris pharetra. Elit at imperdiet dui accumsan. Sodales neque sodales ut etiam sit amet nisl. Suspendisse in est ante in nibh mauris cursus mattis molestie. Tortor at auctor urna nunc id cursus metus aliquam. Risus at ultrices mi tempus imperdiet nulla malesuada pellentesque elit. At erat pellentesque adipiscing commodo elit at. Aliquam id diam maecenas ultricies mi eget mauris pharetra et. Scelerisque viverra mauris in aliquam sem fringilla. Rhoncus urna neque viverra justo. A diam maecenas sed enim ut sem viverra aliquet eget. Fusce ut placerat orci nulla pellentesque. Etiam dignissim diam quis enim lobortis scelerisque fermentum dui. Eu consequat ac felis donec et. Nisl nisi scelerisque eu ultrices vitae auctor eu augue ut. Cras pulvinar mattis nunc sed. Nunc sed velit dignissim sodales ut eu sem. Rutrum tellus pellentesque eu tincidunt tortor aliquam. Nec nam aliquam sem et.

Dolor sed viverra ipsum nunc aliquet bibendum enim facilisis gravida. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus in. Et ligula ullamcorper malesuada proin libero nunc consequat interdum varius. Magna etiam tempor orci eu lobortis elementum nibh tellus molestie. Purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Semper eget duis at tellus at urna condimentum mattis pellentesque. Diam sit amet nisl suscipit adipiscing bibendum est ultricies integer. Sed ullamcorper morbi tincidunt ornare massa. Tellus orci ac auctor augue mauris augue neque gravida in. Ipsum consequat nisl vel pretium lectus quam. Penatibus et magnis dis parturient montes. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. A pellentesque sit amet porttitor eget. Aliquet risus feugiat in ante. Est ultricies integer quis auctor elit sed vulputate. Turpis egestas maecenas pharetra convallis posuere morbi leo. Ut morbi tincidunt augue interdum velit euismod in pellentesque. Semper eget duis at tellus at urna. A diam maecenas sed enim ut sem viverra aliquet. Nunc scelerisque viverra mauris in aliquam sem fringilla ut morbi.', '#virtual #docker #kubernetes', 'images/2019-11-12T00-11-31.324Z-bg-12.jpg', '2019-11-12 00:11:31', '2019-11-12 00:11:31', false, true);
INSERT INTO POSTS (id, user_id, category_id, title, description, tags, image_url, created_at, updated_at, deleted, is_blog) VALUES (5, 'cZLhIvl5csbqk0P8SLhjBE18may1', 1, 'Mobile Android vs IOS', '### This is a fifth post

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique. Diam quis enim lobortis scelerisque fermentum dui. Morbi tristique senectus et netus et malesuada fames. Pretium lectus quam id leo in vitae turpis massa. Suspendisse in est ante in nibh mauris. Id cursus metus aliquam eleifend mi in. Lectus proin nibh nisl condimentum id venenatis a condimentum. Turpis egestas pretium aenean pharetra magna ac placerat. Mauris vitae ultricies leo integer malesuada nunc vel risus commodo. Netus et malesuada fames ac turpis egestas integer eget.

Facilisi nullam vehicula ipsum a arcu cursus. Dolor purus non enim praesent elementum facilisis leo vel. Elementum sagittis vitae et leo. Porttitor eget dolor morbi non arcu risus quis varius quam. Arcu ac tortor dignissim convallis aenean et tortor. Et magnis dis parturient montes nascetur. Varius morbi enim nunc faucibus. Sem nulla pharetra diam sit amet nisl suscipit adipiscing bibendum. Tempor commodo ullamcorper a lacus vestibulum sed arcu non. Consectetur adipiscing elit ut aliquam purus sit amet luctus venenatis.

Proin libero nunc consequat interdum varius sit amet mattis. Platea dictumst quisque sagittis purus sit amet volutpat consequat. Adipiscing commodo elit at imperdiet dui accumsan. Eget aliquet nibh praesent tristique magna. Quis vel eros donec ac. Consequat ac felis donec et odio pellentesque diam volutpat commodo. Blandit libero volutpat sed cras ornare arcu dui. Vulputate mi sit amet mauris commodo quis. Nunc scelerisque viverra mauris in aliquam sem. Erat nam at lectus urna duis convallis. Habitasse platea dictumst vestibulum rhoncus est.

Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Diam maecenas ultricies mi eget mauris pharetra. Elit at imperdiet dui accumsan. Sodales neque sodales ut etiam sit amet nisl. Suspendisse in est ante in nibh mauris cursus mattis molestie. Tortor at auctor urna nunc id cursus metus aliquam. Risus at ultrices mi tempus imperdiet nulla malesuada pellentesque elit. At erat pellentesque adipiscing commodo elit at. Aliquam id diam maecenas ultricies mi eget mauris pharetra et. Scelerisque viverra mauris in aliquam sem fringilla. Rhoncus urna neque viverra justo. A diam maecenas sed enim ut sem viverra aliquet eget. Fusce ut placerat orci nulla pellentesque. Etiam dignissim diam quis enim lobortis scelerisque fermentum dui. Eu consequat ac felis donec et. Nisl nisi scelerisque eu ultrices vitae auctor eu augue ut. Cras pulvinar mattis nunc sed. Nunc sed velit dignissim sodales ut eu sem. Rutrum tellus pellentesque eu tincidunt tortor aliquam. Nec nam aliquam sem et.

Dolor sed viverra ipsum nunc aliquet bibendum enim facilisis gravida. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus in. Et ligula ullamcorper malesuada proin libero nunc consequat interdum varius. Magna etiam tempor orci eu lobortis elementum nibh tellus molestie. Purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Semper eget duis at tellus at urna condimentum mattis pellentesque. Diam sit amet nisl suscipit adipiscing bibendum est ultricies integer. Sed ullamcorper morbi tincidunt ornare massa. Tellus orci ac auctor augue mauris augue neque gravida in. Ipsum consequat nisl vel pretium lectus quam. Penatibus et magnis dis parturient montes. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. A pellentesque sit amet porttitor eget. Aliquet risus feugiat in ante. Est ultricies integer quis auctor elit sed vulputate. Turpis egestas maecenas pharetra convallis posuere morbi leo. Ut morbi tincidunt augue interdum velit euismod in pellentesque. Semper eget duis at tellus at urna. A diam maecenas sed enim ut sem viverra aliquet. Nunc scelerisque viverra mauris in aliquam sem fringilla ut morbi.', '#android #ios', 'images/2019-11-12T00-17-10.553Z-bg-11.jpg', '2019-11-12 00:17:10', '2019-11-12 00:17:10', false, true);
INSERT INTO POSTS (id, user_id, category_id, title, description, tags, image_url, created_at, updated_at, deleted, is_blog) VALUES (6, 'cZLhIvl5csbqk0P8SLhjBE18may1', 5, 'How to ace the Supply chain management', '### This is 6th post

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique. Diam quis enim lobortis scelerisque fermentum dui. Morbi tristique senectus et netus et malesuada fames. Pretium lectus quam id leo in vitae turpis massa. Suspendisse in est ante in nibh mauris. Id cursus metus aliquam eleifend mi in. Lectus proin nibh nisl condimentum id venenatis a condimentum. Turpis egestas pretium aenean pharetra magna ac placerat. Mauris vitae ultricies leo integer malesuada nunc vel risus commodo. Netus et malesuada fames ac turpis egestas integer eget.

Facilisi nullam vehicula ipsum a arcu cursus. Dolor purus non enim praesent elementum facilisis leo vel. Elementum sagittis vitae et leo. Porttitor eget dolor morbi non arcu risus quis varius quam. Arcu ac tortor dignissim convallis aenean et tortor. Et magnis dis parturient montes nascetur. Varius morbi enim nunc faucibus. Sem nulla pharetra diam sit amet nisl suscipit adipiscing bibendum. Tempor commodo ullamcorper a lacus vestibulum sed arcu non. Consectetur adipiscing elit ut aliquam purus sit amet luctus venenatis.

Proin libero nunc consequat interdum varius sit amet mattis. Platea dictumst quisque sagittis purus sit amet volutpat consequat. Adipiscing commodo elit at imperdiet dui accumsan. Eget aliquet nibh praesent tristique magna. Quis vel eros donec ac. Consequat ac felis donec et odio pellentesque diam volutpat commodo. Blandit libero volutpat sed cras ornare arcu dui. Vulputate mi sit amet mauris commodo quis. Nunc scelerisque viverra mauris in aliquam sem. Erat nam at lectus urna duis convallis. Habitasse platea dictumst vestibulum rhoncus est.

Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Diam maecenas ultricies mi eget mauris pharetra. Elit at imperdiet dui accumsan. Sodales neque sodales ut etiam sit amet nisl. Suspendisse in est ante in nibh mauris cursus mattis molestie. Tortor at auctor urna nunc id cursus metus aliquam. Risus at ultrices mi tempus imperdiet nulla malesuada pellentesque elit. At erat pellentesque adipiscing commodo elit at. Aliquam id diam maecenas ultricies mi eget mauris pharetra et. Scelerisque viverra mauris in aliquam sem fringilla. Rhoncus urna neque viverra justo. A diam maecenas sed enim ut sem viverra aliquet eget. Fusce ut placerat orci nulla pellentesque. Etiam dignissim diam quis enim lobortis scelerisque fermentum dui. Eu consequat ac felis donec et. Nisl nisi scelerisque eu ultrices vitae auctor eu augue ut. Cras pulvinar mattis nunc sed. Nunc sed velit dignissim sodales ut eu sem. Rutrum tellus pellentesque eu tincidunt tortor aliquam. Nec nam aliquam sem et.

Dolor sed viverra ipsum nunc aliquet bibendum enim facilisis gravida. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus in. Et ligula ullamcorper malesuada proin libero nunc consequat interdum varius. Magna etiam tempor orci eu lobortis elementum nibh tellus molestie. Purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Semper eget duis at tellus at urna condimentum mattis pellentesque. Diam sit amet nisl suscipit adipiscing bibendum est ultricies integer. Sed ullamcorper morbi tincidunt ornare massa. Tellus orci ac auctor augue mauris augue neque gravida in. Ipsum consequat nisl vel pretium lectus quam. Penatibus et magnis dis parturient montes. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. A pellentesque sit amet porttitor eget. Aliquet risus feugiat in ante. Est ultricies integer quis auctor elit sed vulputate. Turpis egestas maecenas pharetra convallis posuere morbi leo. Ut morbi tincidunt augue interdum velit euismod in pellentesque. Semper eget duis at tellus at urna. A diam maecenas sed enim ut sem viverra aliquet. Nunc scelerisque viverra mauris in aliquam sem fringilla ut morbi.', '#supplychain', 'images/2019-11-12T00-20-16.198Z-bg-8.jpg', '2019-11-12 00:20:16', '2019-11-12 00:20:16', false, true);
INSERT INTO POSTS (id, user_id, category_id, title, description, tags, image_url, created_at, updated_at, deleted, is_blog) VALUES (7, 'cZLhIvl5csbqk0P8SLhjBE18may1', 1, 'Learn React basic', '### This is 8th post

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique. Diam quis enim lobortis scelerisque fermentum dui. Morbi tristique senectus et netus et malesuada fames. Pretium lectus quam id leo in vitae turpis massa. Suspendisse in est ante in nibh mauris. Id cursus metus aliquam eleifend mi in. Lectus proin nibh nisl condimentum id venenatis a condimentum. Turpis egestas pretium aenean pharetra magna ac placerat. Mauris vitae ultricies leo integer malesuada nunc vel risus commodo. Netus et malesuada fames ac turpis egestas integer eget.

Facilisi nullam vehicula ipsum a arcu cursus. Dolor purus non enim praesent elementum facilisis leo vel. Elementum sagittis vitae et leo. Porttitor eget dolor morbi non arcu risus quis varius quam. Arcu ac tortor dignissim convallis aenean et tortor. Et magnis dis parturient montes nascetur. Varius morbi enim nunc faucibus. Sem nulla pharetra diam sit amet nisl suscipit adipiscing bibendum. Tempor commodo ullamcorper a lacus vestibulum sed arcu non. Consectetur adipiscing elit ut aliquam purus sit amet luctus venenatis.

Proin libero nunc consequat interdum varius sit amet mattis. Platea dictumst quisque sagittis purus sit amet volutpat consequat. Adipiscing commodo elit at imperdiet dui accumsan. Eget aliquet nibh praesent tristique magna. Quis vel eros donec ac. Consequat ac felis donec et odio pellentesque diam volutpat commodo. Blandit libero volutpat sed cras ornare arcu dui. Vulputate mi sit amet mauris commodo quis. Nunc scelerisque viverra mauris in aliquam sem. Erat nam at lectus urna duis convallis. Habitasse platea dictumst vestibulum rhoncus est.

Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Diam maecenas ultricies mi eget mauris pharetra. Elit at imperdiet dui accumsan. Sodales neque sodales ut etiam sit amet nisl. Suspendisse in est ante in nibh mauris cursus mattis molestie. Tortor at auctor urna nunc id cursus metus aliquam. Risus at ultrices mi tempus imperdiet nulla malesuada pellentesque elit. At erat pellentesque adipiscing commodo elit at. Aliquam id diam maecenas ultricies mi eget mauris pharetra et. Scelerisque viverra mauris in aliquam sem fringilla. Rhoncus urna neque viverra justo. A diam maecenas sed enim ut sem viverra aliquet eget. Fusce ut placerat orci nulla pellentesque. Etiam dignissim diam quis enim lobortis scelerisque fermentum dui. Eu consequat ac felis donec et. Nisl nisi scelerisque eu ultrices vitae auctor eu augue ut. Cras pulvinar mattis nunc sed. Nunc sed velit dignissim sodales ut eu sem. Rutrum tellus pellentesque eu tincidunt tortor aliquam. Nec nam aliquam sem et.

Dolor sed viverra ipsum nunc aliquet bibendum enim facilisis gravida. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus in. Et ligula ullamcorper malesuada proin libero nunc consequat interdum varius. Magna etiam tempor orci eu lobortis elementum nibh tellus molestie. Purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Semper eget duis at tellus at urna condimentum mattis pellentesque. Diam sit amet nisl suscipit adipiscing bibendum est ultricies integer. Sed ullamcorper morbi tincidunt ornare massa. Tellus orci ac auctor augue mauris augue neque gravida in. Ipsum consequat nisl vel pretium lectus quam. Penatibus et magnis dis parturient montes. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. A pellentesque sit amet porttitor eget. Aliquet risus feugiat in ante. Est ultricies integer quis auctor elit sed vulputate. Turpis egestas maecenas pharetra convallis posuere morbi leo. Ut morbi tincidunt augue interdum velit euismod in pellentesque. Semper eget duis at tellus at urna. A diam maecenas sed enim ut sem viverra aliquet. Nunc scelerisque viverra mauris in aliquam sem fringilla ut morbi.', '#reactjs #node', 'images/2019-11-12T00-21-47.803Z-laptop.jpg', '2019-11-12 00:21:47', '2019-11-12 00:21:47', false, true);
INSERT INTO POSTS (id, user_id, category_id, title, description, tags, image_url, created_at, updated_at, deleted, is_blog) VALUES (8, 'cZLhIvl5csbqk0P8SLhjBE18may1', 1, 'Learn Angular 8', '### This is 8th post

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique. Diam quis enim lobortis scelerisque fermentum dui. Morbi tristique senectus et netus et malesuada fames. Pretium lectus quam id leo in vitae turpis massa. Suspendisse in est ante in nibh mauris. Id cursus metus aliquam eleifend mi in. Lectus proin nibh nisl condimentum id venenatis a condimentum. Turpis egestas pretium aenean pharetra magna ac placerat. Mauris vitae ultricies leo integer malesuada nunc vel risus commodo. Netus et malesuada fames ac turpis egestas integer eget.

Facilisi nullam vehicula ipsum a arcu cursus. Dolor purus non enim praesent elementum facilisis leo vel. Elementum sagittis vitae et leo. Porttitor eget dolor morbi non arcu risus quis varius quam. Arcu ac tortor dignissim convallis aenean et tortor. Et magnis dis parturient montes nascetur. Varius morbi enim nunc faucibus. Sem nulla pharetra diam sit amet nisl suscipit adipiscing bibendum. Tempor commodo ullamcorper a lacus vestibulum sed arcu non. Consectetur adipiscing elit ut aliquam purus sit amet luctus venenatis.

Proin libero nunc consequat interdum varius sit amet mattis. Platea dictumst quisque sagittis purus sit amet volutpat consequat. Adipiscing commodo elit at imperdiet dui accumsan. Eget aliquet nibh praesent tristique magna. Quis vel eros donec ac. Consequat ac felis donec et odio pellentesque diam volutpat commodo. Blandit libero volutpat sed cras ornare arcu dui. Vulputate mi sit amet mauris commodo quis. Nunc scelerisque viverra mauris in aliquam sem. Erat nam at lectus urna duis convallis. Habitasse platea dictumst vestibulum rhoncus est.

Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Diam maecenas ultricies mi eget mauris pharetra. Elit at imperdiet dui accumsan. Sodales neque sodales ut etiam sit amet nisl. Suspendisse in est ante in nibh mauris cursus mattis molestie. Tortor at auctor urna nunc id cursus metus aliquam. Risus at ultrices mi tempus imperdiet nulla malesuada pellentesque elit. At erat pellentesque adipiscing commodo elit at. Aliquam id diam maecenas ultricies mi eget mauris pharetra et. Scelerisque viverra mauris in aliquam sem fringilla. Rhoncus urna neque viverra justo. A diam maecenas sed enim ut sem viverra aliquet eget. Fusce ut placerat orci nulla pellentesque. Etiam dignissim diam quis enim lobortis scelerisque fermentum dui. Eu consequat ac felis donec et. Nisl nisi scelerisque eu ultrices vitae auctor eu augue ut. Cras pulvinar mattis nunc sed. Nunc sed velit dignissim sodales ut eu sem. Rutrum tellus pellentesque eu tincidunt tortor aliquam. Nec nam aliquam sem et.

Dolor sed viverra ipsum nunc aliquet bibendum enim facilisis gravida. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus in. Et ligula ullamcorper malesuada proin libero nunc consequat interdum varius. Magna etiam tempor orci eu lobortis elementum nibh tellus molestie. Purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Semper eget duis at tellus at urna condimentum mattis pellentesque. Diam sit amet nisl suscipit adipiscing bibendum est ultricies integer. Sed ullamcorper morbi tincidunt ornare massa. Tellus orci ac auctor augue mauris augue neque gravida in. Ipsum consequat nisl vel pretium lectus quam. Penatibus et magnis dis parturient montes. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. A pellentesque sit amet porttitor eget. Aliquet risus feugiat in ante. Est ultricies integer quis auctor elit sed vulputate. Turpis egestas maecenas pharetra convallis posuere morbi leo. Ut morbi tincidunt augue interdum velit euismod in pellentesque. Semper eget duis at tellus at urna. A diam maecenas sed enim ut sem viverra aliquet. Nunc scelerisque viverra mauris in aliquam sem fringilla ut morbi.', '#angular', 'images/2019-11-12T06-49-24.908Z-bg-11.jpg', '2019-11-12 06:49:24', '2019-11-12 06:49:24', false, true);
INSERT INTO POSTS (id, user_id, category_id, title, description, tags, image_url, created_at, updated_at, deleted, is_blog) VALUES (9, 'cZLhIvl5csbqk0P8SLhjBE18may1', 1, 'Cloud is not your computer', '### Cloud is someone else computer

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Phasellus vestibulum lorem sed risus. Sit amet mattis vulputate enim nulla aliquet. Nunc mi ipsum faucibus vitae aliquet. Aenean euismod elementum nisi quis eleifend quam. Sed sed risus pretium quam vulputate. Ipsum faucibus vitae aliquet nec. Est ante in nibh mauris cursus mattis molestie. Dui sapien eget mi proin sed. Neque sodales ut etiam sit amet nisl. In tellus integer feugiat scelerisque varius. Enim ut sem viverra aliquet eget sit amet. Id donec ultrices tincidunt arcu non sodales neque sodales. Vitae suscipit tellus mauris a diam maecenas sed enim. Sed turpis tincidunt id aliquet. Donec pretium vulputate sapien nec sagittis aliquam malesuada. Consectetur adipiscing elit duis tristique sollicitudin nibh sit amet.

Varius duis at consectetur lorem donec massa sapien faucibus et. Imperdiet proin fermentum leo vel orci. Habitasse platea dictumst quisque sagittis purus sit amet volutpat consequat. Nunc pulvinar sapien et ligula ullamcorper malesuada proin. Quam vulputate dignissim suspendisse in est ante in nibh mauris. Aliquam etiam erat velit scelerisque. Hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Elementum pulvinar etiam non quam lacus. Cras pulvinar mattis nunc sed blandit libero volutpat sed cras. Diam donec adipiscing tristique risus nec feugiat in fermentum. Velit scelerisque in dictum non. Ipsum suspendisse ultrices gravida dictum fusce. Lacus viverra vitae congue eu consequat ac felis donec et. Sed euismod nisi porta lorem mollis aliquam ut porttitor. Auctor elit sed vulputate mi sit amet mauris commodo. Faucibus turpis in eu mi bibendum neque.

Eleifend donec pretium vulputate sapien. Id nibh tortor id aliquet. Id interdum velit laoreet id donec ultrices tincidunt arcu non. Orci eu lobortis elementum nibh tellus molestie. Nibh sit amet commodo nulla facilisi. Fermentum dui faucibus in ornare. Velit euismod in pellentesque massa placerat duis ultricies lacus. Pharetra diam sit amet nisl suscipit adipiscing bibendum. Orci dapibus ultrices in iaculis. Porta nibh venenatis cras sed felis eget velit aliquet. Tortor at auctor urna nunc id cursus. Hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. In massa tempor nec feugiat nisl pretium fusce id velit. Convallis a cras semper auctor. Vitae aliquet nec ullamcorper sit amet risus nullam. Arcu vitae elementum curabitur vitae nunc. Eget egestas purus viverra accumsan in. Orci phasellus egestas tellus rutrum tellus. Malesuada fames ac turpis egestas integer eget. Libero nunc consequat interdum varius sit.

Consequat nisl vel pretium lectus quam id leo in vitae. Malesuada fames ac turpis egestas integer eget. Tortor consequat id porta nibh venenatis cras. Lacus sed turpis tincidunt id. Pharetra vel turpis nunc eget. Nulla at volutpat diam ut venenatis. Non enim praesent elementum facilisis. Ultrices gravida dictum fusce ut. Nibh sed pulvinar proin gravida hendrerit lectus a. Lectus proin nibh nisl condimentum id venenatis. Auctor urna nunc id cursus metus aliquam eleifend mi in. Ultrices in iaculis nunc sed augue lacus. Commodo odio aenean sed adipiscing diam donec adipiscing tristique risus. Leo a diam sollicitudin tempor id. Sed libero enim sed faucibus turpis. Sollicitudin nibh sit amet commodo. Amet porttitor eget dolor morbi non arcu risus. Mi in nulla posuere sollicitudin aliquam ultrices sagittis. In ante metus dictum at tempor commodo ullamcorper a lacus. Mattis molestie a iaculis at erat.', '#cloud', 'images/2019-11-12T16-55-56.483Z-mountain.png', '2019-11-12 16:55:56', '2019-11-12 16:55:56', false, true);
DROP TABLE RATING;
CREATE TABLE RATING (user_id varchar(200) NOT NULL, post_id int NOT NULL, rating tinyint NOT NULL, PRIMARY KEY (post_id, user_id), INDEX user_id (user_id)) ENGINE=InnoDB DEFAULT CHARSET=latin1 DEFAULT COLLATE=latin1_swedish_ci;
DROP TABLE TAGS;
CREATE TABLE TAGS (name varchar(255) NOT NULL, PRIMARY KEY (name)) ENGINE=InnoDB DEFAULT CHARSET=latin1 DEFAULT COLLATE=latin1_swedish_ci;
INSERT INTO TAGS (name) VALUES ('#android');
INSERT INTO TAGS (name) VALUES ('#angular');
INSERT INTO TAGS (name) VALUES ('#bctax');
INSERT INTO TAGS (name) VALUES ('#cloud');
INSERT INTO TAGS (name) VALUES ('#computer');
INSERT INTO TAGS (name) VALUES ('#docker');
INSERT INTO TAGS (name) VALUES ('#ios');
INSERT INTO TAGS (name) VALUES ('#kubernetes');
INSERT INTO TAGS (name) VALUES ('#lamp');
INSERT INTO TAGS (name) VALUES ('#nicepicture');
INSERT INTO TAGS (name) VALUES ('#node');
INSERT INTO TAGS (name) VALUES ('#reactjs');
INSERT INTO TAGS (name) VALUES ('#supplychain');
INSERT INTO TAGS (name) VALUES ('#unix');
INSERT INTO TAGS (name) VALUES ('#virtual');
DROP TABLE USERS;
CREATE TABLE USERS (id varchar(200) NOT NULL, username varchar(50), full_name text, is_active tinyint(1) DEFAULT 1 NOT NULL, PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=latin1 DEFAULT COLLATE=latin1_swedish_ci;
INSERT INTO USERS (id, username, full_name, is_active) VALUES ('cZLhIvl5csbqk0P8SLhjBE18may1', 'quangle', 'Quang Le', true);
ALTER TABLE `ATTACHMENTS` ADD FOREIGN KEY (`post_id`) REFERENCES `POSTS` (`id`);
ALTER TABLE `COMMENTS` ADD FOREIGN KEY (`post_id`) REFERENCES `POSTS` (`id`) ;
ALTER TABLE `COMMENTS` ADD FOREIGN KEY (`reply_id`) REFERENCES `COMMENTS` (`id`);
ALTER TABLE `POSTS` ADD FOREIGN KEY (`user_id`) REFERENCES `USERS` (`id`) ;
ALTER TABLE `POSTS` ADD FOREIGN KEY (`category_id`) REFERENCES `CATEGORIES` (`id`);
ALTER TABLE `RATING` ADD FOREIGN KEY (`post_id`) REFERENCES `POSTS` (`id`) ;
ALTER TABLE `RATING` ADD FOREIGN KEY (`user_id`) REFERENCES `USERS` (`id`);
